name: mobile_app
description: A new Flutter project.

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  speech_to_text: ^6.6.2
  youtube_player_flutter: ^8.1.2
  just_audio: ^0.9.9+1
  audio_service: 0.18.13
  fluttertoast: ^8.0.9 
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.1.1
  intl: ^0.18.1
  google_speech: 5.2.0+1
  image: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true

  assets:
    - assets/lang/

