// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaTwnsaiLD5iwEg5McSzcVf47DaqyS0xo',
    appId: '1:801168488690:web:2dd3a00c372ff635cf786b',
    messagingSenderId: '801168488690',
    projectId: 'finalseniorproject-83a2c',
    authDomain: 'finalseniorproject-83a2c.firebaseapp.com',
    storageBucket: 'finalseniorproject-83a2c.appspot.com',
    measurementId: 'G-VBJ38YY7ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB67ykzg3VegB7WcRZmo7i-dXPgANSGXeg',
    appId: '1:801168488690:android:66fd413d6c28a39fcf786b',
    messagingSenderId: '801168488690',
    projectId: 'finalseniorproject-83a2c',
    storageBucket: 'finalseniorproject-83a2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXk22yoaCMP5kVei_JiUNUH6MuYQi6GwE',
    appId: '1:801168488690:ios:b8a5c665bfb660f3cf786b',
    messagingSenderId: '801168488690',
    projectId: 'finalseniorproject-83a2c',
    storageBucket: 'finalseniorproject-83a2c.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXk22yoaCMP5kVei_JiUNUH6MuYQi6GwE',
    appId: '1:801168488690:ios:b8a5c665bfb660f3cf786b',
    messagingSenderId: '801168488690',
    projectId: 'finalseniorproject-83a2c',
    storageBucket: 'finalseniorproject-83a2c.appspot.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaTwnsaiLD5iwEg5McSzcVf47DaqyS0xo',
    appId: '1:801168488690:web:da2e0b1bcf39985acf786b',
    messagingSenderId: '801168488690',
    projectId: 'finalseniorproject-83a2c',
    authDomain: 'finalseniorproject-83a2c.firebaseapp.com',
    storageBucket: 'finalseniorproject-83a2c.appspot.com',
    measurementId: 'G-QCS4PXCHSD',
  );
}
